In [2]:
import pandas as pd
df = pd.read_csv("data/internships.csv")

In [3]:
df.columns

Index(['Company', 'Job Title', 'Location', 'Job Type', 'Experience', 'Skill 1',
       'Skill 2', 'Skill 3', 'Skill 4', 'Skill 5', 'Skill 6', 'Perk 1',
       'Perk 2', 'Perk 3', 'Perk 4', 'Perk 5', 'Perk 6'],
      dtype='object')

In [4]:
df = df[[
    "Job Title",
    "Location",
    "Experience",
    "Skill 1", "Skill 2", "Skill 3", "Skill 4", "Skill 5", "Skill 6"
]]

In [5]:
df = df.dropna(subset=["Job Title"])

In [6]:
df["Job Title"] = df["Job Title"].str.lower().str.strip()
df["Location"] = df["Location"].str.lower().str.strip()

In [7]:
skill_cols = ["Skill 1", "Skill 2", "Skill 3", "Skill 4", "Skill 5", "Skill 6"]

df["skills"] = df[skill_cols].fillna("").agg(", ".join, axis=1)

df["skills"] = df["skills"].str.lower()

In [8]:
df = df.drop_duplicates()

In [9]:
df.head()
df.shape

(211, 10)

In [10]:
df.columns

Index(['Job Title', 'Location', 'Experience', 'Skill 1', 'Skill 2', 'Skill 3',
       'Skill 4', 'Skill 5', 'Skill 6', 'skills'],
      dtype='object')

In [11]:
df.head()

,Job Title,Location,Experience,Skill 1,Skill 2,Skill 3,Skill 4,Skill 5,Skill 6,skills
0,data science intern- undergrad (summer 2023),"san jose, ca, united states",Entry-level,Agile,Architecture,Data analysis,Data Analytics,Data strategy,Data visualization,"agile, architecture, data analysis, data analy..."
1,r&d data scientist intern (alternance),"nice, provence-alpes-côte d'azur, france",Entry-level,Big Data,Computer Science,Deep Learning,Engineering,Keras,Python,"big data, computer science, deep learning, eng..."
2,alternance data analyst (h/f),"cluses, france",Entry-level,Data analysis,Excel,Power BI,Python,R,R&D,"data analysis, excel, power bi, python, r, r&d"
3,mlops engineer intern (alternance),"nice, provence-alpes-côte d'azur, france",Entry-level,Azure,Big Data,CI/CD,Computer Science,Databricks,Deep Learning,"azure, big data, ci/cd, computer science, data..."
4,data scientist (nlp & ml) intern (alternance),"nice, provence-alpes-côte d'azur, france",Entry-level,Azure,Big Data,C++,Computer Science,Deep Learning,Docker,"azure, big data, c++, computer science, deep l..."

In [12]:
skill_cols = ["Skill 1", "Skill 2", "Skill 3", "Skill 4", "Skill 5", "Skill 6"]

df["Skills"] = (
    df[skill_cols]
    .fillna("")                 # remove NaN
    .agg(", ".join, axis=1)     # join skills
    .str.replace(r"(, )+", ", ", regex=True)
    .str.strip(", ")
)

In [13]:
df.drop(columns=skill_cols, inplace=True)

In [14]:
df.columns

Index(['Job Title', 'Location', 'Experience', 'skills', 'Skills'], dtype='object')

In [15]:
df.head()

,Job Title,Location,Experience,skills,Skills
0,data science intern- undergrad (summer 2023),"san jose, ca, united states",Entry-level,"agile, architecture, data analysis, data analy...","Agile, Architecture, Data analysis, Data Analy..."
1,r&d data scientist intern (alternance),"nice, provence-alpes-côte d'azur, france",Entry-level,"big data, computer science, deep learning, eng...","Big Data, Computer Science, Deep Learning, Eng..."
2,alternance data analyst (h/f),"cluses, france",Entry-level,"data analysis, excel, power bi, python, r, r&d","Data analysis, Excel, Power BI, Python, R, R&D"
3,mlops engineer intern (alternance),"nice, provence-alpes-côte d'azur, france",Entry-level,"azure, big data, ci/cd, computer science, data...","Azure, Big Data, CI/CD, Computer Science, Data..."
4,data scientist (nlp & ml) intern (alternance),"nice, provence-alpes-côte d'azur, france",Entry-level,"azure, big data, c++, computer science, deep l...","Azure, Big Data, C++, Computer Science, Deep L..."

In [16]:
df.drop(columns=["skills"], inplace=True)

In [17]:
df.columns

Index(['Job Title', 'Location', 'Experience', 'Skills'], dtype='object')

In [18]:
df.columns = df.columns.str.strip()

In [19]:
df.shape

(211, 4)

In [20]:
df.head(211)

,Job Title,Location,Experience,Skills
0,data science intern- undergrad (summer 2023),"san jose, ca, united states",Entry-level,"Agile, Architecture, Data analysis, Data Analy..."
1,r&d data scientist intern (alternance),"nice, provence-alpes-côte d'azur, france",Entry-level,"Big Data, Computer Science, Deep Learning, Eng..."
2,alternance data analyst (h/f),"cluses, france",Entry-level,"Data analysis, Excel, Power BI, Python, R, R&D"
3,mlops engineer intern (alternance),"nice, provence-alpes-côte d'azur, france",Entry-level,"Azure, Big Data, CI/CD, Computer Science, Data..."
4,data scientist (nlp & ml) intern (alternance),"nice, provence-alpes-côte d'azur, france",Entry-level,"Azure, Big Data, C++, Computer Science, Deep L..."
...,...,...,...,...
223,data management unit intern,"nakuru, kenya",Entry-level,"Consulting, Data analysis, Data management, Da..."
224,machine learning intern,"bengaluru, karnataka, india",Entry-level,"BERT, Elasticsearch, GPT, Keras, Machine Learn..."
225,"applied research, machine learning - phd summe...","mountain view, california (hq)",Entry-level,"Autonomous Driving, Computer Science, Deep Lea..."
226,"summer internship, research scientist, audio i...",berlin,Entry-level,"Computer Science, Engineering, GitHub, Machine..."
227,internship: deep learning based lane and road ...,"leonberg, germany",Entry-level,"Agile, Computer Science, Computer Vision, Deep..."

In [21]:
def assign_domain(text):
    text = str(text).lower()

    ai_keywords = [
        "machine learning", "deep learning", "artificial intelligence",
        "nlp", "computer vision", "ml", "ai"
    ]

    data_keywords = [
        "data analyst", "data science", "data scientist",
        "data analysis", "analytics", "big data"
    ]

    web_keywords = [
        "web", "frontend", "backend", "full stack",
        "react", "angular", "html", "css", "javascript"
    ]

    cloud_keywords = [
        "cloud", "aws", "azure", "gcp", "devops", "kubernetes", "docker"
    ]

    for kw in ai_keywords:
        if kw in text:
            return "AI"

    for kw in data_keywords:
        if kw in text:
            return "Data"

    for kw in web_keywords:
        if kw in text:
            return "Web"

    for kw in cloud_keywords:
        if kw in text:
            return "Cloud"

    return "Other"


# apply on Job Title + Skills together (best practice)
df["domain"] = (
    df["Job Title"].astype(str) + " " + df["Skills"].astype(str)
).apply(assign_domain)

df.head()

,Job Title,Location,Experience,Skills,domain
0,data science intern- undergrad (summer 2023),"san jose, ca, united states",Entry-level,"Agile, Architecture, Data analysis, Data Analy...",Data
1,r&d data scientist intern (alternance),"nice, provence-alpes-côte d'azur, france",Entry-level,"Big Data, Computer Science, Deep Learning, Eng...",AI
2,alternance data analyst (h/f),"cluses, france",Entry-level,"Data analysis, Excel, Power BI, Python, R, R&D",Data
3,mlops engineer intern (alternance),"nice, provence-alpes-côte d'azur, france",Entry-level,"Azure, Big Data, CI/CD, Computer Science, Data...",AI
4,data scientist (nlp & ml) intern (alternance),"nice, provence-alpes-côte d'azur, france",Entry-level,"Azure, Big Data, C++, Computer Science, Deep L...",AI

In [22]:
df["domain"].value_counts()

domain
AI       112
Data      80
Other     14
Cloud      4
Web        1
Name: count, dtype: int64

In [23]:
df.head()

,Job Title,Location,Experience,Skills,domain
0,data science intern- undergrad (summer 2023),"san jose, ca, united states",Entry-level,"Agile, Architecture, Data analysis, Data Analy...",Data
1,r&d data scientist intern (alternance),"nice, provence-alpes-côte d'azur, france",Entry-level,"Big Data, Computer Science, Deep Learning, Eng...",AI
2,alternance data analyst (h/f),"cluses, france",Entry-level,"Data analysis, Excel, Power BI, Python, R, R&D",Data
3,mlops engineer intern (alternance),"nice, provence-alpes-côte d'azur, france",Entry-level,"Azure, Big Data, CI/CD, Computer Science, Data...",AI
4,data scientist (nlp & ml) intern (alternance),"nice, provence-alpes-côte d'azur, france",Entry-level,"Azure, Big Data, C++, Computer Science, Deep L...",AI

In [24]:
df.head(10)

,Job Title,Location,Experience,Skills,domain
0,data science intern- undergrad (summer 2023),"san jose, ca, united states",Entry-level,"Agile, Architecture, Data analysis, Data Analy...",Data
1,r&d data scientist intern (alternance),"nice, provence-alpes-côte d'azur, france",Entry-level,"Big Data, Computer Science, Deep Learning, Eng...",AI
2,alternance data analyst (h/f),"cluses, france",Entry-level,"Data analysis, Excel, Power BI, Python, R, R&D",Data
3,mlops engineer intern (alternance),"nice, provence-alpes-côte d'azur, france",Entry-level,"Azure, Big Data, CI/CD, Computer Science, Data...",AI
4,data scientist (nlp & ml) intern (alternance),"nice, provence-alpes-côte d'azur, france",Entry-level,"Azure, Big Data, C++, Computer Science, Deep L...",AI
5,data analyst / data scientist intern (h/f/x) -...,paris,Entry-level,"Agile, Clustering, Data analysis, Data visuali...",Data
6,data science intern,"redwood city, california, united states",Entry-level,"Avro, AWS, Computer Science, CSV, DynamoDB, Fi...",Data
7,data scientist - internship,"paris, france",Entry-level,"A/B testing, Engineering, Machine Learning, ML...",AI
8,data scientist intern,"united states, remote",Entry-level,"APIs, Big Data, Business Analytics, Data analy...",Data
9,data analytics intern,"san francisco, ca",Entry-level,"Banking, Data Analytics, Data visualization, D...",Data

In [26]:
df.to_csv("data/internships_cleaned.csv", index=False)